### ISSUE TITLE
Serverside Crash 1.10.2 - Release FTGU-1.10.2-b1.1.2.jar

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [TheRActivator/From-the-Ground-Up#10]
https://gist.github.com/P3rf3ctXZer0/b2fb4690f9c03a6bbe69a313b3db97b9

**Comment by Astavie** [comment]
This error seems to come from the StructPro mod. Since it is a mod about buildings and schematics, I don't see how this could come from FTGU

**Comment by P3rf3ctXZer0** [comment]
Try asking questions help from ternsip https://minecraft.curseforge.com/projects/structpro-mod-fast-schematic-spawning-system you will need to pm him.
