### ISSUE TITLE
Need all none researched recipes hidden in JEI

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [TheRActivator/From-the-Ground-Up#11]
Would it be too much trouble to ask that you hide all JEI recipes that have not been researched?

**Comment by Astavie** [comment]
I cannot hide recipes using the JEI API but I can hide items in the list.
Well - I _can_ hide recipes (by literally removing them at the client side and re-adding them once you've unlocked them) and I may do that in the future, but I don't have the time or energy to do that right now.

**Comment by Astavie** [comment]
I'll keep this issue open until I'll get onto what I mentioned above

**Comment by Astavie** [comment]
closing this because I don't actually plan on doing what I said I would do since there's a lot of grey area and it's just complicated.

**Comment by SHsuperCM** [comment]
Any chance that you would please re-open this? This is really bad that you see recipes and when you try to do 'em they don't work..

I suggest you look at the source of GameStages addon for items
https://github.com/Darkhax-Minecraft/ItemStages

It actually removes the items from JEI in `net.darkhax.itemstages.jei.PluginItemStages`

**Comment by P3rf3ctXZer0** [comment]
If this mod does not hide recipes not yet researched - it defeats the point of the mods very existence. Sad you have given up. I say a ton of adventuring and pack making potential. :/

**Comment by Astavie** [comment]
IIRC GameStages only hides the items from the filter, not when you press 'r' on the item. Also, FTGU used to hide items from the filter, but it seems I removed it. I'm not sure why actually. I can re-add it, but I'm not sure how to hide recipes.

**Comment by SHsuperCM** [comment]
Wasn't asking for just the recipes.. IMO hiding the items as well means that you literally don't know what they are in the game until you've unlocked them, making the JEI item list a list of memory of items.
