### ISSUE TITLE
White screen on start

### ISSUE THREAD

**Issue by darkfr3ak** [TheRActivator/From-the-Ground-Up#17]
Hey :) Got an strange problem when using FTGU: Minecraft starts fine, no shown Errors, but then instead of the Main Menu, I get a white screen. If I remove FTGU it's normal.

My Modlist:

<ul>
<li><a href="https://minecraft.curseforge.com/mc-mods/254970">DynamicSounds (by ArabTears)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/228027">BiblioCraft (by JDSinclair)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/74924">Mantle (by mDiyo)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/70496">BdLib (by bdew)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/239197">CraftTweaker (by jaredlll08)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/70492">Gendustry (by bdew)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/230976">Fast Leaf Decay (by Olafskii)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/220318">Biomes O' Plenty (by Glitchfiend)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/240630">Just Enough Resources (JER) (by Way2muchnoise)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/220954">ModTweaker (by jaredlll08)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/242818">CodeChicken Lib 1.8.+ (by covers1624)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/231951">Immersive Engineering (by BluSunrize)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/224535">IvToolkit (by Ivorforce)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/248370">JEI Bees (by bdew)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/238222">Just Enough Items (JEI) (by mezz)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/59751">Forestry (by SirSengir)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/231868">EnderCore (by tterrag1098)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/64578">Ender IO (by CrazyPants_MC)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/233071">Crafting Tweaks (by BlayTheNinth)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/223094">Inventory Tweaks (by Kobata)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/32274">JourneyMap (by techbrew)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/69162">CoFH Core (by TeamCoFH)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/232391">EIORecipesTEInductionSmelter (by XFactHD)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/253211">MTLib (by jaredlll08)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/67133">VeinMiner (by Portablejim)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/253043">WanionLib (by WanionCane)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/69163">Thermal Expansion (by TeamCoFH)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/223150">Recurrent Complex (by Ivorforce)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/246010">Simple Generators (by ValkyrieofNight)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/250226">More Bees (by Lach_01298)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/60089">Mouse Tweaks (by YaLTeR97)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/74072">Tinkers Construct (by mDiyo)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/237989">Realistic Terrain Generation (by WhichOnesPink)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/253462">Steve's Carts Reborn (by modmuss50)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/79287">Waila Harvestability (by squeek502)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/221585">Roguelike Dungeons (by Greymerk)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/242739">Scenter Mod (by MickKay)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/245480">ValkyrieLib (by ValkyrieofNight)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/73488">Waila (by ProfMobius)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/253338">Steve's Factory Manager Reborn (by Gigabit1011)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/237414">RealBench (by Prototik)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/222880">Thermal Foundation (by TeamCoFH)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/244258">UniDict (by WanionCane)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/246996">B.A.S.E (by lanse505)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/242001">ArchitectureCraft (by gcewing)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/243883">Chicken Chunks 1.8.+ (by covers1624)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/243822">CodeChicken Core 1.8.+ (by covers1624)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/256717">Clumps (by jaredlll08)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/237167">FTBLib (by FTB)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/59816">Random Things (by lumien231)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/223896">MalisisCore (by Ordinastie)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/229503">Tinker I/O (by gkbm2011)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/224712">Wawla - What Are We Looking At (by darkh4x)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/223891">MalisisDoors (by Ordinastie)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/246320">Environmental Creepers (by masa_)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/255177">YABBA (by LatvianModder)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/231347">Mo' Bends (by iwoplaza)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/238551">GraveStone Mod (by EuhDawson)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/235442">Modular Powersuits (by MachineMuse)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/227083">Baubles (by azanor)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/245506">Minecolonies (by Kostronor)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/225643">Botania (by Vazkii)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/227049">Iron Backpacks (by gr8pefish)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/70631">Redstone Arsenal (by TeamCoFH)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/246640">Mystical Agriculture (by BlakeBr0)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/237903">Reborn Core (by modmuss50)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/248498">Technical Dimensions (by modmuss50)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/247393">Simple Quarry (by MrDimkas_Studio)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/257814">CreativeCore (by CreativeMD)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/258587">ItemPhysic (by CreativeMD)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/261199">Animania (by Purplicious_Cow)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/244181">Block Drops (JEI Addon) (by MrRiegel)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/224428">ThutCore (by patnevis)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/224375">Thut's Elevators (by patnevis)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/243298">LLibrary (by iLexiconn)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/226719">JurassiCraft2 (by gegy)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/264684">Dirt2Path (by marwat208)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/237749">CoroUtil (by Corosus)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/237746">Weather, Storms & Tornadoes (by Corosus)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/250711">LimeLib (by MrRiegel)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/239336">Furnus (by MrRiegel)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/227325">AD - Reforged Resource Pack (by kyctarniq)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/235279">Chisel (by tterrag1098)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/225946">LootBags (by Malorolam)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/225561">Extra Utilities (by RWTema)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/251396">InfinityLib (by InfinityRaider)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/225635">AgriCraft (by InfinityRaider)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/229060">iChunUtil (by iChun)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/220606">Progressive Automation (by VanhalMinecraft)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/232758">Cyclops Core (by kroeser)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/247007">Common Capabilities (by kroeser)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/236307">Integrated Dynamics (by kroeser)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/251389">Integrated Tunnels (by kroeser)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/224808">Magneticraft (by cout970)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/248042">Cyberware (by stuntrally)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/229084">Portal Gun (by iChun)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/78778">Chest Transporter (by CubeX2)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/228756">Iron Chests (by progwml6)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/245388">Claycraft (by Blubbeltasche)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/227276">Clay WorldGen (by EwyBoy)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/258131">Tool Upgrades Mod (by XxRexRaptorxX)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/258944">Customized Dungeon Loot (by XxRexRaptorxX)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/246795">ViesCraft - Airships! (by Viesis_Gaming)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/231254">Giacomo's Foundry (by Zacomat)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/254916">Engineers Workshop (by EwyBoy)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/235577">TrashSlot (by BlayTheNinth)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/262691">ExU2 - Cursed Earth Ritual (by voxatu)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/241895">KleeSlabs (by BlayTheNinth)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/247496">Ranged Pumps (by raoulvdberge)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/223008">OpenComputers (by SangarWasTaken)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/233564">Tech Reborn (by modmuss50)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/257330">ToroQuest (by ToroCraft)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/244249">Simple Ore Generation (by RohzekTheScientist)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/239431">MCMultiPart (by amadornes)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/243076">Refined Storage (by raoulvdberge)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/251792">Simply Jetpacks 2 (by Tomson124)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/256247">Mystical Agradditions (by BlakeBr0)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/265640">Huds - Armor Status & Damage Indicators (by Elec332)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/227391">ElecCore | Rendering Library (by Elec332)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/254508">Bed Bugs (by gr8pefish)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/242998">Silent Lib (by SilentChaos512)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/230238">Super Multi-Drills (by SilentChaos512)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/266081">Timberjack (by CovertJaguar)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/255389">EnhancedVisuals (by CreativeMD)</a></li>
<li><a href="https://minecraft.curseforge.com/mc-mods/250717">From the Ground Up (by HeroWorkbrine)</a></li>
</ul>

**Comment by Astavie** [comment]
Do you have a console log I can look at?

**Comment by Astavie** [comment]
closing this for now
