### ISSUE TITLE
Game stuck on world loading

### ISSUE THREAD

**Issue by meelock** [TheRActivator/From-the-Ground-Up#18]
Whenever I load a world for the second time ftgu appears to send an invalid packet, this causes the game to hang at 0%.

log: [Paste](http://paste.ubuntu.com/24476769/)

**Comment by SamuelDancing** [comment]
same thing happens to me with atlantic survival

i guess this mod is still in the bug fixing stage

**Comment by Astavie** [comment]
I cannot recreate this, so it seems some other mod is interfering with the packet. As far as I know it seems that somehow the client-side player variable inside the Minecraft class is set to null, which it shouldn't be...
Could you both give me a mod list?

**Comment by meelock** [comment]
Output of dir in terminal, hope this helps!

05/07/2017  11:38 AM    <DIR>          .
05/07/2017  11:38 AM    <DIR>          ..
04/25/2017  06:08 PM         2,967,909 achievementbooks-v1.0-MC1.11.2.jar
04/20/2017  05:34 PM            29,675 AppleSkin-mc1.11-1.0.6.jar
04/30/2017  02:29 PM           253,990 Architect-MC1.11.2-1.0.5.48.jar
04/27/2017  04:32 PM           156,366 Aroma1997Core-1.11.2-1.2.0.0.jar
04/27/2017  04:32 PM           109,213 AromaBackup-1.11-2.1.0.0.jar
04/20/2017  05:41 PM        12,393,619 astralsorcery-1.3.2-beta.jar
04/20/2017  05:35 PM            56,170 AutoRegLib-1.1-4.jar
05/02/2017  07:15 PM           104,445 Baubles-1.11-1.4.4.jar
05/01/2017  09:41 PM         2,025,073 Better With Mods-1.1.7-1.11.2.jar
04/20/2017  05:35 PM            63,985 BetterAchievements-1.11.2-0.4.3.12.jar
05/06/2017  10:55 AM         4,662,160 BetterFoliage-MC1.11.2-2.1.5.jar
05/04/2017  07:34 PM           148,785 BetterFps-1.4.4.jar
05/06/2017  10:55 AM         6,352,750 BiomesOPlenty-1.11.2-6.1.0.2211-universal.jar
04/24/2017  08:59 PM        13,852,847 Botania r1.9-343.jar
05/05/2017  11:50 PM         3,706,196 buildcraft-7.99.1-178.jar
04/20/2017  05:34 PM            95,003 Chameleon-1.11-3.0.2.jar
04/20/2017  05:34 PM        17,115,847 Chisel-MC1.11.2-0.0.10.14.jar
04/20/2017  05:34 PM           650,086 chiselsandbits-13.10.jar
04/30/2017  02:29 PM           219,272 ColossalChests-1.11.2-1.5.2.jar
04/25/2017  06:20 PM           155,322 CommonCapabilities-1.11.2-1.3.2.jar
05/02/2017  07:16 PM            38,568 compatlayer-1.11.2-0.2.8.jar
04/20/2017  05:34 PM           817,120 CraftTweaker-1.11.2-3.0.24.jar
04/28/2017  02:10 PM           826,796 cyberware-1.11.2-alpha-0.2.9.jar
04/25/2017  06:20 PM           714,480 CyclopsCore-1.11.2-0.10.2.jar
05/01/2017  09:41 PM        13,396,776 Decocraft-2.4.2_1.11.2.jar
05/05/2017  11:42 PM        12,756,002 DynamicSurroundings-1.11.2-3.4.1.0.jar
04/20/2017  05:42 PM           848,043 ElecCore-1.11-1.7.418.jar
04/28/2017  02:09 PM         1,518,985 embers-0.210.jar
04/29/2017  06:57 PM            37,030 EnchantingTable-1.11-1.1.jar
04/20/2017  05:43 PM           224,082 endertanks-1.11.0-1.5.4.jar
04/25/2017  05:59 PM         3,581,910 EvilCraft-1.11.2-0.10.24.jar
04/22/2017  10:04 PM         1,140,789 fairylights-2.1.0-1.11.2.jar
04/25/2017  07:50 PM             5,213 FastLeafDecay-v12.jar
04/23/2017  12:14 PM         3,446,034 FluxedRedstone-2.6.0.54.jar
04/20/2017  05:49 PM           142,752 foamfix-0.6.2-beta4-anarchy.jar
05/03/2017  08:05 PM         4,147,480 forestry_1.11.2-5.3.3.96.jar
04/22/2017  10:07 PM           160,991 FTGU-1.11.2-b1.1.4.jar.disabled
04/25/2017  06:08 PM           178,946 GiacomosBookshelf-1.11.2-1.1.jar
04/25/2017  06:09 PM           146,664 GiacomosMaps-1.11.2-1.2.2.jar
04/25/2017  06:10 PM            46,479 GiacomosTravelogue-1.11.2-1.0.4.jar
04/20/2017  05:34 PM           487,963 Hwyla-1.8.13-B26_1.11.jar
04/23/2017  11:12 AM    <DIR>          ic2
04/23/2017  06:52 PM         6,944,172 industrialcraft-2-2.7.12-ex111.jar
05/07/2017  11:38 AM             8,701 InitialInventory-2.0.2.jar
04/25/2017  06:20 PM         2,640,208 IntegratedDynamics-1.11.2-0.6.12.jar
04/25/2017  05:53 PM           255,407 IntegratedTunnels-1.11.2-1.1.2.jar
04/24/2017  09:09 PM           151,685 ironchest-1.11.2-7.0.18.800.jar
04/20/2017  05:40 PM            16,787 itemzoom1.11.2-1.5.jar
05/03/2017  08:05 PM           508,937 jei_1.11.2-4.3.4.273.jar
04/20/2017  05:33 PM         1,732,680 journeymap-1.11.2-5.4.6.jar
04/23/2017  08:05 PM            33,181 MTLib-2.0.1.jar
04/20/2017  05:43 PM           835,931 multistorage-1.11.0-1.3.6.jar
04/24/2017  08:59 PM           210,741 NotEnoughPotions-1.3_for_1.11.2.jar
04/28/2017  06:42 PM        14,049,914 OpenComputers-MC1.11.2-1.7.0.13.jar
04/29/2017  02:38 PM           493,247 paintings-1.11-3.2.1.1.jar
04/24/2017  08:59 PM           176,733 PotionCore-1.5.1_for_1.11.2.jar
04/24/2017  09:21 PM            72,997 PSG Revamper-1.11-1.0.0.0.jar
05/03/2017  07:09 AM            88,995 QualityTools-1.0.3_for_1.11.2.jar
05/03/2017  08:06 PM         1,407,500 Quark-r1.2-91.jar
04/21/2017  08:30 PM         1,920,898 RandomThings-MC1.11.2-3.8.1.jar
04/23/2017  12:14 PM         1,613,274 RebornCore-1.11.2-2.14.2.94-universal.jar
04/23/2017  12:21 PM            90,398 redstonepaste-mc1.11.2-1.7.4.jar
04/27/2017  04:42 PM         1,583,501 refinedstorage-1.4.4.jar
04/21/2017  08:12 PM         1,092,956 Reliquary-1.11.2-1.3.3.653.jar
04/20/2017  05:37 PM           683,457 roots-2-0.016.jar
04/20/2017  05:43 PM           372,855 shetiphiancore-1.11.0-3.4.4.jar
04/30/2017  02:29 PM           555,089 StorageDrawers-1.11.2-4.2.3.jar
04/22/2017  10:04 PM            47,864 StructuredCrafting-1.11.2-0.1.7.jar
04/23/2017  01:57 PM    <DIR>          test
04/24/2017  09:08 PM           580,720 TIS-3D-MC1.11.2-1.2.0.39.jar
04/26/2017  06:54 PM           139,182 TombManyGraves-1.11.2-3.0.7.jar
04/20/2017  05:34 PM            31,665 WailaHarvestability-mc1.11-1.1.9.jar
05/06/2017  11:30 AM           165,344 WearableBackpacks-1.11.2-2.3.2.jar
              71 File(s)    148,286,835 bytes
               4 Dir(s)  825,499,877,376 bytes free

**Comment by Astavie** [comment]
Sorry for the long wait...
I can make a temporary fix by not sending the packet if the player is null, but this will cause some desyncs when the player joins. It should be fine once the player opens the research book.

**Comment by Astavie** [comment]
[This zip file](https://github.com/TheRActivator/From-the-Ground-Up/files/1031578/ftgu.zip) contains updated versions of ftgu. Do they fix the issue? @meelock @SamuelDancing

**Comment by SamuelDancing** [comment]
i uninstalled it from the pack because it is incompatible with wearable backpacks and maybe also custom NPCs and no it does not work

**Comment by Astavie** [comment]
@SamuelDancing I am asking you if it _works_ with your pack, not if you want to re-add it.

**Comment by SamuelDancing** [comment]
updated the comment also i will compile a list of mods that could be causing the issue eventually

**Comment by SamuelDancing** [comment]
i think i've narrowed it down to four mods
compatlayer
Cyclops Core
eleccore rendering library
jei
these are the mods that are consistent besides FTGU obviously and from my experience it happens when you load another world after loading one (or world jumping) you may have to do it more than once

**Comment by Astavie** [comment]
I implemented the possible fix in 1.1.5. Closing this for now.
