### ISSUE TITLE
Client crash on mouse over magnifying glass in JEI

### ISSUE THREAD

**Issue by GazbonicAcid** [TheRActivator/From-the-Ground-Up#2]
My client crashes whenever I hover my mouse cursor over the magnifying (used for research scanning) in JEI.
[ATLauncher Console Log](http://pastebin.com/8dhwBEf6)
[fml-client-latest.log](http://pastebin.com/sKdVZ8tV)
[latest.log](http://pastebin.com/yWAZbDjj)

**Comment by Astavie** [comment]
Ah yes, I can probably guess why this is happening. I'll make a note and fix it asap

**Comment by Astavie** [comment]
Okay, it should be fixed now. I'm going add a new release soon
