### ISSUE TITLE
Can't craft some items

### ISSUE THREAD

**Issue by msathieu** [TheRActivator/From-the-Ground-Up#20]
Even with all research done, I can't craft notch apples or shulker boxes. Can't you make all blocks without research craftable?

**Comment by Astavie** [comment]
Notch apples have been uncraftable since 1.9. Not sure why you can't craft shulker boxes though...

**Comment by Astavie** [comment]
I can craft shulker boxes just fine...? Are you sure you have the right recipe?

**Comment by msathieu** [comment]
I mean enchanted golden apples for the achievement.

**Comment by Astavie** [comment]
You need to find and eat an enchanted golden apple in a dungeon chest I think, because they have been uncraftable since 1.9

**Comment by msathieu** [comment]
Sorry, I was using an old crafting guide.
