### ISSUE TITLE
Commands for adding/removing/resetting player's technologies ?

### ISSUE THREAD

**Issue by Ksehn** [TheRActivator/From-the-Ground-Up#21]
Hi @TheRActivator,

Is it possible to create a command for "editing" player's technologies like the vanilla command [/achievement](http://minecraft.gamepedia.com/Commands#achievement), but for From the Ground Up's technologies ? 

This command could be used from commands blocks (or others mods who can run console command, like CustomNpcs), for rewarding players with "unlockable" technologies added throught CraftTweaker ( By the way, thanks you for this mod and his CraftTweaker support °-° ! ).

**Comment by Astavie** [comment]
Will probably do when forge comes out for 1.12 (was already planning on doing something like this).

**Comment by Ksehn** [comment]
Yeay !

Also, do you plan to port your futures additions to the 1.10.2 version ?

**Comment by Astavie** [comment]
Yes, but I'll probably stop supporting 1.10 once 1.12 comes out (feature-wise, game breaking bugs will still be fixed).

**Comment by Ksehn** [comment]
That's really cool 👍 

I don't know how much times is needed to port features from a version to another, but I was a bit worried if the newest features of FTGU were only available on the latest version ( I'm actually "stuck" at the '1.10 with mods like Ars Magica, Bibliocraft, Ice and Fire, and soon (I hope x3), Thaumcraft :p )

**Comment by Astavie** [comment]
Oh uh before you get your hopes up I do want to specify that I do _not_ plan on porting the 1.12-related features (JSON loading and making the research book look like the advancement screen)

**Comment by Ksehn** [comment]
Yes, of course ^^'

**Comment by meelock** [comment]
Maybe in the future, FtGU might allow for advancements to be based on research, as well as having built-in advancement packs. Just a thought.

**Comment by Astavie** [comment]
Added in 1.2.3 (experimental version)
Sorry for taking so long, and I don't think I'm going to support 1.10 and 1.11 anymore
