### ISSUE TITLE
Configuration option to allow/disallow the copy feature ?

### ISSUE THREAD

**Issue by Ksehn** [TheRActivator/From-the-Ground-Up#22]
Hi,

What do you think about adding an option in the configuration file of FtGU to allow or disallow the copy feature from the Research Book ?

![copy](https://cloud.githubusercontent.com/assets/11042301/26603532/6cdf31ea-4587-11e7-828d-09c3758297d3.jpg)

... and sorry if there is already a way to prevent this '-'

**Comment by Ksehn** [comment]
Or maybe change the "copy state" (Allowed/Unallowed) of a technology using a new boolean parameter with CraftTweaker ?

**Comment by Astavie** [comment]
Added in 1.2.3 (experimental version)
Sorry for taking so long, and I don't think I'm going to support 1.10 and 1.11 anymore
