### ISSUE TITLE
From the Ground Up - Not Understanding - Help would be Awesome!

### ISSUE THREAD

**Issue by ChipsAhoyMcCoy16** [TheRActivator/From-the-Ground-Up#26]
Alright.

I attempt to follow the CraftTweaker support from here:
https://github.com/TheRActivator/From-the-Ground-Up/wiki/CraftTweaker-Support#pages

I do not exactly understand. I keep receiving the error for no such member.
I know I have given very little. This is my first post and I am struggling to understand.

**Comment by Astavie** [comment]
You are indeed giving very little... What is your code?

**Comment by ChipsAhoyMcCoy16** [comment]
Okay. Let me try to start over with what I have attempted, now that I am a little level headed now and not so frustrated.

Giving some better background knowledge, and some obvious things.
I wanted to use the "From the Ground Up" mod in my minecraft. I also wanted to use other mods and combine the "From the Ground Up" experience with other mods.

I saw that "From the Ground Up" had "Native CraftTweaker Support".
So in turn, I followed this link to the code to use to allow that addition of pages and technologies:
https://github.com/TheRActivator/From-the-Ground-Up/wiki/CraftTweaker-Support#pages

I then followed the tutorials from here:
http://minetweaker3.powerofbytes.com/wiki/Main_Page
That way, I would have some knowledge of how to work this mod.

Also want to add, I also added the mod, "ModTweaker".

So the process I went through, was that I added the basic code for adding a new page, just to test the mod.
The specific code was: 
mods.ftgu.Page.addPage

But once I got a weird Java exception error, I realized I needed a ;

The next change to the code was to this:
mods.ftgu.Page.addPage;

Which results in:
![2017-06-19_18 24 16](https://user-images.githubusercontent.com/29504942/27308448-97393a7c-551c-11e7-88d6-a096dafa1b72.png)

So, I also realize that this code requires an argument. Now I am new to coding and I do not fully understand the definition of an argument and what they are supposed to look like.

But the next piece of code I tried was:
import mods.ftgu.Page.addPage("Test Page");

Which results in:
![2017-06-19_18 28 45](https://user-images.githubusercontent.com/29504942/27308572-431ff6e6-551d-11e7-872f-26eced897f82.png)

 I hope this is much more to work off of. Thank you for the reply.  If you need more info, just ask!

**Comment by Astavie** [comment]
You just have to do `mods.ftgu.Page.addPage("Test Page");`, no import required.
Import is used like this:
```
import mods.ftgu.Page;
Page.addPage("Test Page 1");
Page.addPage("Test Page 2");
```
I think, at least

**Comment by ChipsAhoyMcCoy16** [comment]
I attempted to use the code you suggested and I got this error:
![2017-06-20_19 03 28](https://user-images.githubusercontent.com/29504942/27359757-8af38ec8-55eb-11e7-91e0-479c75ec3da2.png)
![2017-06-20_19 03 30](https://user-images.githubusercontent.com/29504942/27359764-8f9c65f8-55eb-11e7-9a36-b06f52a73f66.png)

I then try to use the import version and I get this error:
![2017-06-20_19 07 42](https://user-images.githubusercontent.com/29504942/27359824-e4df3fc2-55eb-11e7-94f9-8c7614ca1d8d.png)

![2017-06-20_19 07 50](https://user-images.githubusercontent.com/29504942/27359826-e98930fa-55eb-11e7-826d-db28559c446f.png)

![2017-06-20_19 07 52](https://user-images.githubusercontent.com/29504942/27359828-ecb6d8b8-55eb-11e7-9ab6-f927de3f70f7.png)

**Comment by Ksehn** [comment]
Hi @ChipsAhoyMcCoy16,

Are you sure you're running the latest version of From the Ground Up ?
The error in your screens remind me this: #23 (Actually fixed by TheRActivator in FtGU 1.1.5).

**Comment by Astavie** [comment]
@ChipsAhoyMcCoy16 yeah you might be using an outdated version if it doesn't recognise `ftgu` as a member

**Comment by ChipsAhoyMcCoy16** [comment]
I lowered my game version to 1.10.2 along with the mods. It seemed to have worked.
I was running on 1.11.2 before with the mods and that is where I kept getting the errors.
