### ISSUE TITLE
Some problems in researching ideas

### ISSUE THREAD

**Issue by Rinma** [TheRActivator/From-the-Ground-Up#27]
Ok, i have the parchment for carpentry research and the only thing i don't get is the middle block/item on the researcher. It says "block chopper" so i think it is an axe. I had a look at the java code and as it looks for me the block/item that is missing is an axe. The problem is i can first build an axe after i researched carpentry.

I use Minecraft 1.11.2 and FTGU-1.11.2-b1.1.6
![bildschirmfoto von 2017-06-17 20-38-09](https://user-images.githubusercontent.com/1405824/27255344-f6eb90a4-539c-11e7-8298-c1e7b5ce5fe5.png)
![bildschirmfoto von 2017-06-17 20-38-13](https://user-images.githubusercontent.com/1405824/27255345-f6f14558-539c-11e7-842c-73166e47194f.png)

**Comment by Rinma** [comment]
Also on stoneworking i have a "?" on all nine fields but as i get it it should only be on the tree fields on the top and the two in the middle. The other fields show now text but a resource string that has no value.

![bildschirmfoto von 2017-06-17 20-37-25](https://user-images.githubusercontent.com/1405824/27255347-01044f18-539d-11e7-9ebc-53d588b8c60f.png)
![bildschirmfoto von 2017-06-17 20-37-43](https://user-images.githubusercontent.com/1405824/27255349-013205fc-539d-11e7-97e2-b6dd898f8aba.png)
![bildschirmfoto von 2017-06-17 20-37-37](https://user-images.githubusercontent.com/1405824/27255348-0108e9ce-539d-11e7-8415-0a0aee379d04.png)

**Comment by Astavie** [comment]
1. Stoneworking unlocks the stone axe, which you can use for the carpentry research
2. That second thing is a bug...

**Comment by adlingtont** [comment]
I am also experiencing the second bug.

**Comment by Astavie** [comment]
fixed in 1.1.7
