### ISSUE TITLE
CraftTweaker Integration

### ISSUE THREAD

**Issue by GazbonicAcid** [TheRActivator/From-the-Ground-Up#3]
I would like to request CraftTweaker integration to allow the customization of the research process, and to allow pack authors and such to add unsupported recipes/crafting-processes.
For example, the "[Rice Crafting Table](https://minecraft.curseforge.com/projects/rice-crafting-table)", or various processing machines from various tech mods.

**Comment by Astavie** [comment]
I'll look into what I can do, nice suggestion either way

**Comment by TheRActivator** [comment]
Alright, it should be fixed now! I'll release a new version soon.

**Comment by Astavie** [comment]
Sorry for the commits, I meant to put fixed #2 there :|

**Comment by Astavie** [comment]
After thinking about it I don't think the issue section is a good place for requests, so I'm closing this for now. I am planning on adding crafttweaker integration though
