### ISSUE TITLE
Lack of documentation

### ISSUE THREAD

**Issue by GazbonicAcid** [TheRActivator/From-the-Ground-Up#30]
1.12 changelog says moved away from crafttweaker to json system.
But no default jsons are generated,
and JSON page on wiki is empty/not-made.
Please actually document it or the 1.12 version is useless to pack-devs.

**Comment by Astavie** [comment]
For now you can view all vanilla technologies [here](https://github.com/TheRActivator/From-the-Ground-Up/tree/1.12/src/main/resources/assets/ftgumod/technologies), but yeah, I do need to add some documentation

**Comment by Astavie** [comment]
Documentation added
