### ISSUE TITLE
1.12 default issue

### ISSUE THREAD

**Issue by darkshadow543** [TheRActivator/From-the-Ground-Up#31]
The default survival is activated at the start of a new world in 1.12.2.

**Comment by Astavie** [comment]
Every player has researched "survival" and "research" at the start. Works as intended.

**Comment by darkshadow543** [comment]
I guess you need proof, where here it is.  https://www.youtube.com/watch?v=0KthsTHV-3A&feature=youtu.be  I started a new world just to show you.

**Comment by Astavie** [comment]
"This video is unavailable"
