### ISSUE TITLE
[1.12.2] Automatic researches not granted at game start

### ISSUE THREAD

**Issue by ReverseStateMonad** [TheRActivator/From-the-Ground-Up#33]
Forge Version: 1.12.2-14.23.0.2517
Mod Version: 1.12.2-b1.2.4

Upon starting a new world, the Survival and Research technologies are not researched.  This means that I have no recipes available to craft, and am unable to research anything.  The technologies _are_ present, and if I have cheats active I can use the /technology command to grant them to myself.

**Comment by Enderborn1235** [comment]
Do have a log so that the author can track down where he went wrong?

**Comment by Astavie** [comment]
No need, [I found the problem](https://github.com/Astavie/From-the-Ground-Up/blob/67da86fb5c93a5040e1f853c72b944033d40cf24/src/main/java/ftgumod/technology/Technology.java#L525). That "researchedAtStart" should just be "start" so this should be easy to fix.
