### ISSUE TITLE
Crash when opening the research book (1.12.2)

### ISSUE THREAD

**Issue by henrique-klayton** [TheRActivator/From-the-Ground-Up#34]
When I open the research book the game crash
I am using only the ftgu b1.2.5
The config is:

Copy= false
Custom= true
I don't have any custom technologies

Crash Report:

[https://pastebin.com/8y9vMXEc](https://pastebin.com/8y9vMXEc)

**Comment by Astavie** [comment]
1. Temporary fix is to add a custom technology
2. But it still shouldn't crash, so yes, bug fixing time
