### ISSUE TITLE
Half of researches not working

### ISSUE THREAD

**Issue by ilvrak** [TheRActivator/From-the-Ground-Up#35]
FTGU-1.12.2-b1.2.5
I'm checked several technologies from the sourse json from your mod and they do not work:
Refinement
Dyes
Carts
Stonemasonry

**Comment by Astavie** [comment]
Could you elaborate on them "not working"?

**Comment by GazbonicAcid** [comment]
He means we put in the research recipe, and it's not "researching" it.
Such as the Refinement research.
![refinement_not_working](https://user-images.githubusercontent.com/492596/32455714-ae2732cc-c2e8-11e7-883a-e8ad00c74772.png)
That's the refinement research parchment, the center-center is iron ore, the bottom-center is coal, and the other's are cobble-stone.

**Comment by ilvrak** [comment]
Yes, exactly.
and i don't verify techs after this on techtree.
i tested on clear mc with only ftgu and jei. forge 2528

**Comment by Astavie** [comment]
That's strange... I'll work on it this week.
