### ISSUE TITLE
No Global Support?

### ISSUE THREAD

**Issue by Sixdd6** [TheRActivator/From-the-Ground-Up#37]
With the old Craft-tweaker support we could make a modpack and have support for ftgu in every save, now everything is tied to the save folder. Why the change and is there a way to make the mod work across all saves?

**Comment by Astavie** [comment]
Minecraft 1.13 will add Data Packs, but https://minecraft.curseforge.com/projects/copy-paste can be used as a temporary fix.

**Comment by Sixdd6** [comment]
Ah, fantastic. Thank You.
