### ISSUE TITLE
Make .json cusomization a config

### ISSUE THREAD

**Issue by darkshadow543** [TheRActivator/From-the-Ground-Up#38]
From a pack makers perspective, having the modification take place in the save folder is not a very good idea.  We want to customize a players experience, and not our own.  Might be good for a specific map, but not so good in terms where the player makes their own world which has its own save.  It would be nicer for customization if it were in the config and not the save file.  This as also the reason triumph was made, because then we could have custom achievements affect every world instead of one.  Also, we should be able to make our own subgroups.

**Comment by Astavie** [comment]
https://minecraft.curseforge.com/projects/copy-paste (see #37)
And you're already able to make your own subgroups/trees. If the tree folder isnt named `survival`, `research`, `power` or `construction`, it will become a new tree in the research book

**Comment by Astavie** [comment]
Also, the reason it's inside the save folder and not, like you suggested, the config folder, is because this system is modelled after advancements, and because sometimes someone does want something to be linked to only one world.
