### ISSUE TITLE
Game Stages support

### ISSUE THREAD

**Issue by ReverseStateMonad** [TheRActivator/From-the-Ground-Up#39]
Have you considered adding the ability to allow research to interact with the [Game Stages ](https://minecraft.curseforge.com/projects/game-stages) mod?  In particular this would allow things like unlocking Tinkers Construct materials/tool types individually, or unlocking features in Waila (via the TinkerStages and Waila Stages addons respectively).

**Comment by Astavie** [comment]
Download [experimental release 1.2.7](https://github.com/Astavie/Astavie.github.io/raw/mvn-repo/astavie/ftgu/1.12.2-b1.2.7/ftgu-1.12.2-b1.2.7.jar) for GameStages support
```javascript
{
  "display": {},
  "gamestage": "insert required stage here",
  "idea": {},
  "reseach": {},
  "unlock": [
    {
      "type": "gamestages:stage",
      "stage": "insert stage that is given here"
    }
  ]
}
```
