### ISSUE TITLE
[b1.2.7] Experimental version hard dependency on Immersive Engineering

### ISSUE THREAD

**Issue by ReverseStateMonad** [TheRActivator/From-the-Ground-Up#41]
I downloaded the experimental version to try out the Game Stages support, and it crashes without Immersive Engineering present (`java.lang.NoClassDefFoundError: blusunrize/immersiveengineering/common/blocks/BlockIEBase at ftgumod.FTGU.postInit(FTGU.java:141)`).

I can provide the full crash report if that's not enough info, but that seems to be everything relevant; it looks like that line needs to be inside the conditional immediately preceding it, although I couldn't say if any additional changes would be needed elsewhere.

**Comment by Astavie** [comment]
Right, seems I execute some IE compatibility code outside the if statement that checks if it's loaded

**Comment by Astavie** [comment]
Should be fixed in experimental version b1.2.8
