### ISSUE TITLE
Documentation is very lacking

### ISSUE THREAD

**Issue by GazbonicAcid** [TheRActivator/From-the-Ground-Up#42]
New gamestages support is undocumented.
I am intensely interested in how to use this new support.
I assume the support means I can add a "stage" as a "reward" so to speak to be added to the player completing the research?
And because I tend to go into too much detail,
an example being setting tinkers lumber axes to the stage "lumberaxe" and a FTGU research completion giving the "researcher" the "lumberaxe" stage.
If that is how it works I will most definitely try adding FTGU and game stage mods to my modpack "Artifex Arcanus".

**Comment by GazbonicAcid** [comment]
Looking at the source it looks like I add something like this.
```
  "stage": "gamestage"
```
Here's an example using the current json technology example as a base.
```
{
  "display": {
    // Display data
  },
  "parent": "insert id here",
  "idea": {
    // Idea recipe
  },
  "research": {
    // Research recipe
  },
  "unlock": [
    {
      // Item 1
    },
    {
      // Item 2
    }
  ],
  "stage": "Enter GameStage to unlock here"
}
```

**Comment by Astavie** [comment]
Did I take half a year to do this? Yes. Was that necessary? No. Can I turn back time? No.
