### ISSUE TITLE
Research Journal

### ISSUE THREAD

**Issue by GazbonicAcid** [TheRActivator/From-the-Ground-Up#43]
I would like to request you add the ability to share completed researches via a craftable "Research Journal".
I would suggest that it works thus.
Person A crafts journal.
All of the research Person A has completed at the time of crafting is saved via nbt to the crafted journal.
Person B uses the journal, gaining the completed researches saved to the journal.
Person B keeps any researches that they have previously completed that were not completed in Person A's journal.
I feel you should give pack makes a config option to choose whether these journals are infinite, limited-use-durability, or one-use-only.

**Comment by NotAVerb** [comment]
Isn't that what parchment with a copied research is for?
