### ISSUE TITLE
Results in crafting table/player inventory is invisible

### ISSUE THREAD

**Issue by charlescannon** [TheRActivator/From-the-Ground-Up#47]
Tested with b1.3.7 and last few versions of forge.

**Comment by Astavie** [comment]
Do you mean that when you craft an item in the crafting table or player inventory the result is invisible until you click on it?
Does this still occur once you've opened the research book? (This usually syncs the server and client)
If not, what other mods are you using?

**Comment by charlescannon** [comment]
No other mods. Sometimes the results stay invisible and and the ingredients stay in crafting grid. until I try adding more ingredients. But usually it does appear when I click on them. 

I'll double check if the book changes things.

**Comment by charlescannon** [comment]
Yeah, it's the book thing.  Thank you.

**Comment by Astavie** [comment]
I'll leave the issue up until I've made the syncing seamless
