### ISSUE TITLE
Research Table Crash

### ISSUE THREAD

**Issue by thanasishadow** [TheRActivator/From-the-Ground-Up#50]
I put a feather, a magnifying glass and a written parchment (which i got from JEI) in a research table, the game crashed and I can't log in the world.

https://pastebin.com/agW5zf7d

**Comment by Astavie** [comment]
I don't recommend putting a parchment from JEI in the research table

**Comment by thanasishadow** [comment]
Yeah, I figured that out when it was too late.
Would it be possible to hide that item from JEI so nobody else attempts it?
