### ISSUE TITLE
Adding more constants results into a crash

### ISSUE THREAD

**Issue by henrique-klayton** [TheRActivator/From-the-Ground-Up#56]
I can't add more constants to the _constants file. The crash doesn't gives a crashlog but throws some errors.

Minecraft 1.12.2
FTGU b1.3.15

latest.log
https://pastebin.com/hz58D2Xm

**Comment by Astavie** [comment]
> The string is too long for this encoding

Oh... Well, this will be hard to fix. Going to have to refactor the packets then.
