### ISSUE TITLE
Lock recipes for Artisans Worktable.

### ISSUE THREAD

**Issue by Xorbah** [TheRActivator/From-the-Ground-Up#58]
Title. Is there any method of locking recipes on these tables as well, since functionality wise they're similar to vanilla crafting tables?

I referenced this issue on their Github as well. The link for the mod is found at Curseforge at the following link -

https://minecraft.curseforge.com/projects/artisan-worktables?gameCategorySlug=mc-mods&projectID=284351

**Comment by Astavie** [comment]
As this has been implemented in Artisan Integrations, I am now closing this.
