### ISSUE TITLE
Please put it in the curse/curseforge page that FTGU is allowed in modpacks.

### ISSUE THREAD

**Issue by GazbonicAcid** [TheRActivator/From-the-Ground-Up#6]
> TheRActivator [https://github.com/TheRActivator/From-the-Ground-Up/issues/5#issuecomment-267795964](https://github.com/TheRActivator/From-the-Ground-Up/issues/5#issuecomment-267795964)
Also yes, this mod is free to use in any modpack if you give me credit in some visible way (like linking to the curseforge page)

Could you please add this to the curse/curseforge page?
The license set on it is "All Rights Reserved" and you don't sate anything about if it's allowed in modpacks else-where on the curse/curseforge page.

**Comment by Astavie** [comment]
Just added that :)
