### ISSUE TITLE
Couldn't be together with Pyrotech

### ISSUE THREAD

**Issue by God-Arthur** [TheRActivator/From-the-Ground-Up#61]
(My English is poor)
Hello,I'm a mods pack maker from China.Nowadays I found that a mod made From The Ground Up couldn't work.It's big mod,called pyrotech.After pyrotech setup,the research_table of FTGU didn't work.Before that,all machines worked normally,normally and normally.Why was that?I've asked the owner of Pyrotech,he told me to modify FTGU recipes,how to do that?Help me,please!I'll thank you very much!

**Comment by God-Arthur** [comment]
My question is namely how does the code of research and research table work,it's mainly the JSON files in the FTGU.jar\assets\ftgumod\technology\construction directory. What's the definition of the code in the following picture?
![image](https://user-images.githubusercontent.com/42578454/64488807-ce474400-d27e-11e9-80fc-c22a80639d18.png)
What do these lines of codes mean?

**Comment by Astavie** [comment]
Sorry for the late answer...

We have a wiki page you can look at ([https://github.com/Astavie/From-the-Ground-Up/wiki/Technologies](https://github.com/Astavie/From-the-Ground-Up/wiki/Technologies))

If you have more questions, do ask.
