### ISSUE TITLE
Minor crashes

### ISSUE THREAD

**Issue by wootaboot** [TheRActivator/From-the-Ground-Up#62]
[crash-2020-04-27_13.27.15-client.txt](https://github.com/Astavie/From-the-Ground-Up/files/4541556/crash-2020-04-27_13.27.15-client.txt)

everytime game loads and unlock new research options this crash pops. not sure what is causing it.

**Comment by Astavie** [comment]
Does this new build fix it? [download FTGU version 1.4.1](https://github.com/Astavie/Astavie.github.io/raw/mvn-repo/astavie/ftgu/1.12.2-b1.4.1/ftgu-1.12.2-b1.4.1.jar)

**Comment by wootaboot** [comment]
yep that seems to solve the issue, thanks
