### ISSUE TITLE
Crash when loading game

### ISSUE THREAD

**Issue by vizthex123** [TheRActivator/From-the-Ground-Up#65]
I enabled the config option where only the configs load (and not the default research), made my own custom research (trying to piece together the guide's directions, before just copy/pasting one from the code and changing the values), but the game crashes.

It's quite annoying because there's no support discord, nor any other documentation about the mod other than the wiki here (which is pretty good, but it separates the entire .json structure into chunks which makes piecing it together quite annoying. It would be nice if at the end of the technologies guide, an entire example file was provided)

Here are the relevant files:
[FTGUCrash.zip](https://github.com/Astavie/From-the-Ground-Up/files/6224479/FTGUCrash.zip)

**Comment by Astavie** [comment]
There *is* a discord! It's mentioned at the bottom of the curseforge page.

For the rest, I agree the documentation is a bit lacking. The problem with your own tech is that the id of the fishing rod is "fishing_rod" and not "fishing_pole". Still, this should not result in a crash.

**Comment by vizthex123** [comment]
Ah ok, will try that. Thanks.

It'd be great if the home page of the wiki had the Discord, or the footer.

**Comment by Astavie** [comment]
Apart from this, other issues thatll need to be fixed sometime:
- [x] Idea Table shift-click support
- [ ] config option to disable parchment being returned
- [ ] config option to show entire tree at all times
- [x] better error messages (in chat, even)

**Comment by Astavie** [comment]
Alright, I think I fixed the crash

**Comment by vizthex123** [comment]
Nice, thanks.
