### ISSUE TITLE
FTGU does not recognize oredictionary, and fails to lock items/blocks in the 2x2 grid

### ISSUE THREAD

**Issue by GazbonicAcid** [TheRActivator/From-the-Ground-Up#7]
The CraftTweaker does not work with ore-dictionary entries.
Also it completely fails to lock the blocks and items in CraftTweaker added technologies.
Please note however that it is only broken with regards to using ore-dictionary, and the actual blocking of items/blocks before the technology is researched.
With the exception of a lack of ore-dictionary support,
the actual addition of technologies, ideas, research, and scrambled hints all work perfectly.

**Comment by Astavie** [comment]
Hello again.
I just tested the CraftTweaker support again and I have no idea what you are talking about, actually... Could you post what you are actually doing in your script file? Ore dictionary is done with \<ore:ingotIron\> in minetweaker, if you got that wrong.

I tested with this line: "mods.ftgu.Technology.addTechnology("Minecraft", null, \<minecraft:dye:0\>, 10, 5, "the_holy_ink_sac", [\<minecraft:dye:0\>,\<minecraft:wool:15\>,\<ore:ingotIron\>]);"

**Comment by Astavie** [comment]
Also the tech icon does not support ore dictionary, because the ore dictionary generally outputs multiple items (and the icon should just be one item). But the rest should include ore dict

**Comment by GazbonicAcid** [comment]
I've tried both of these.
Only the one not using ore dictionary worked as expected.
[Without](http://hastebin.com/tufarekuwo.lua)
[With](http://hastebin.com/upohurutov.scala)
The one with ore dictionary did **_not_** let me get an idea, nor research after I switched the idea to using the item name directly.

**Comment by Astavie** [comment]
I finally get what the problem is: the sand contained in \<ore:sand\> has a metadata of... 32767... Which is why it isn't equal to the regular sand which has a metadata of 0. This is a problem with forge, not FTGU (because the oredict gravel has a normal metadata of 0). To get around this problem you can add \<minecraft:sand:0\> to \<ore:sand\> yourself.

**Comment by Astavie** [comment]
For extra proof: here is your idea recipe but with sand with metadata 32767: https://i.gyazo.com/5a2e20a78821b8b1581a1c114473207e.png

**Comment by Astavie** [comment]
Also, the locking of recipes only works in the vanilla crafting table (very sorry to say that). I _can_ try to add some TC compatibility by extending it to the crafting station as well.

**Comment by GazbonicAcid** [comment]
I only tried in vanilla inventory crafting grid.

**Comment by Astavie** [comment]
I got no clue why the locking isn't working for you. I'll probably have to add TC to my workspace to test this out with modded items and blocks. Also the sand "bug" isn't a bug, and I take full responsibility for it. I now get why the oredictionary is wierd sometimes and I am currently going to fix it.

**Comment by Astavie** [comment]
I just tested _exactly_ the minetweaker code you posted and it works fine for me - apart from the oredictionary bug I still have to fix. It locks the grout recipe like it's supposed to: https://i.gyazo.com/b554ffdb7599741551b2131aa1764042.png

Are the vanilla recipes even locking for you? Also, what other mods are you using? (maybe one conflicts with FTGU)

**Comment by GazbonicAcid** [comment]
[Township Farms Dev_012](https://www.atlauncher.com/pack/TownshipFarms/)
And I haven't bothered to check vanilla stuff yet.
I also didn't try it in the vanilla crafting table.

**Comment by GazbonicAcid** [comment]
Probably the "Progression" mod to be honest that's conflicting.
Why I didn't think to remove it for testing FTGU since I'm wanting to replace it with FTGU anyway is beyond me.
I'll remove Progression and try again.

**Comment by Astavie** [comment]
Ah, right! Yes, there is a bug where you can craft things in the 2x2 crafting grid in your inventory... I should probably fix that too....

**Comment by GazbonicAcid** [comment]
At least it locks the 3x3 crafting table

**Comment by Astavie** [comment]
That's good to hear! I am releasing the next experimental version tomorrow probably, which will fix the 2x2 crafting grid, and the oredictionary.
- [x] Fix the ore dictionary recognition
- [x] Add locking to the 2x2 grid

**Comment by Astavie** [comment]
A new experimental release is available, which fixes this issue!
