### ISSUE TITLE
Can't take Parchment

### ISSUE THREAD

**Issue by ghost** [TheRActivator/From-the-Ground-Up#9]
[Unable to create an idea parchment. Parchment and sometimes all items in the Idea table will disappear.](https://gyazo.com/de9e85f97c2ee6fe500a41102b4e5d04)

**Comment by Astavie** [comment]
- What mods are you using
 - Is this your first research

**Comment by ghost** [comment]
I had a hand full of mods, but I figured it out. it's not your mod it was [Visible Armor Slots](https://minecraft.curseforge.com/projects/visible-armor-slots?gameCategorySlug=mc-mods&projectID=244589). The mod seems to be poorly coded.
